/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author hecto
 */
public class creacionDeUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form creacionDeUsuarios
     */
    public creacionDeUsuarios() {
        initComponents();
        
    }
    
    static ArrayList <HumanSequencePlayer> users = new ArrayList<>();
    static RandomAccessFile dataBase;
    menu menu = new menu();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreCompleto = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        confirmPass = new javax.swing.JPasswordField();
        regresar = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreCompleto.setBackground(new java.awt.Color(153, 0, 0));
        nombreCompleto.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        nombreCompleto.setForeground(new java.awt.Color(255, 255, 255));
        nombreCompleto.setBorder(null);
        jPanel1.add(nombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 185, 30));

        confirmar.setBackground(new java.awt.Color(153, 0, 0));
        confirmar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        confirmar.setForeground(new java.awt.Color(255, 255, 255));
        confirmar.setText("Confirmar");
        confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        jPanel1.add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 272, 150, 30));

        pass.setBackground(new java.awt.Color(153, 0, 0));
        pass.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setBorder(null);
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 185, 30));

        confirmPass.setBackground(new java.awt.Color(153, 0, 0));
        confirmPass.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        confirmPass.setForeground(new java.awt.Color(255, 255, 255));
        confirmPass.setBorder(null);
        confirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassActionPerformed(evt);
            }
        });
        jPanel1.add(confirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 185, 30));

        regresar.setBackground(new java.awt.Color(153, 0, 0));
        regresar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setText("Regresar");
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 140, 30));

        user.setBackground(new java.awt.Color(153, 0, 0));
        user.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setBorder(null);
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 185, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Plantillas/CREACIONDEUSUARIOS.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void confirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassActionPerformed

    public static boolean exists(String user){
        for (HumanSequencePlayer current : users){
            if (current.getUsername().equals(user)){
                return true;
            }
        }
        
        return false;
    }
    
    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        setVisible(false);
        
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_regresarActionPerformed
    
    
    public static String usersToString(){
        String accum = "";
        
        for (int i = 0; i < users.size(); i++) {
            accum += users.get(i).getPlayerName()+ "\n";
        }
        
        return accum;
    }
    
    public static void poblarUsers() throws IOException{
        users = new ArrayList<>();
        
        //Asegura el puntero
        dataBase.seek(0);
        
        while (dataBase.getFilePointer() < dataBase.length()){ //Recorrido de archivo
            dataBase.readUTF(); //Mueve el puntero la cantidad de Bytes que abarque el Nombre Completo del user
            dataBase.skipBytes(12); //Skip 4 (int puntos) + 8 (long fecha) = 12 bytes
            String username = (String)dataBase.readUTF();
            
            HumanSequencePlayer player = new HumanSequencePlayer(users.size() + 1, username);
            
            users.add(player);
            dataBase.readUTF(); //Mueve el puntero la cantidad de Bytes que abarque el password del usuario

        }
    }
    
    /*
    Formato de dataBase.db
    
    String Nombre Completo
    int puntos
    long Fecha de creacion
    String username
    String password
    */
    
    public static void addUser(String nombreCompleto, String username, String password) throws IOException {
        //Setea el archivo en el que vamos a escribir
        dataBase = new RandomAccessFile("dataBase.db", "rw");
        
        dataBase.seek(dataBase.length()); //Setea el puntero al final del archivo
        dataBase.writeUTF(nombreCompleto); //Escribe el nombre completo
        dataBase.writeInt(0); //Escribe la cantidad inicial de puntos
        dataBase.writeLong(Calendar.getInstance().getTimeInMillis()); //Escribe la fecha de creacion
        dataBase.writeUTF(username); //Escribe el username
        dataBase.writeUTF(password); //Escribe el password
    }
    
    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
      

        //Extraccion de los datos de los text fields
        String nombre = nombreCompleto.getText();
        String username = user.getText();
        String password = String.valueOf(pass.getPassword());
        String confirmPassword  = String.valueOf(confirmPass.getPassword());

        if (!exists(username)){ //Verifica que el usuario exista, si no existe, procede a validar para crear otro
            if (password.equals(confirmPassword)){ //Verifica que los passwords en ambos espacios sean identicos
                //Crea el username en el archivo dataBase.db
                try {
                    addUser(nombre, username, password);

                    //Agrega el user a una lista interna de users que solo contiene los usernames para verificar que sean unicos
                    //Se borra mas tarde si este ya existe

                    users.add(login.userWithUsername(username));

                    JOptionPane.showMessageDialog(null, "Usuario ha sido creado con exito!");

                    //Cambia de ventana al menu
                    setVisible(false);

                    menu.setVisible(true);
                    menu.setLocationRelativeTo(null);

                } catch (IOException e){ //Necesario ya que estamos lidiando con RandomAccessFile
                    JOptionPane.showMessageDialog(null, "Ocurrio un error, intente de nuevo");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden. Intente de nuevo.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Este usuario ya existe. Intente de nuevo");
        }
    }//GEN-LAST:event_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPass;
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreCompleto;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
