/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;

/**
 *
 * @author hecto
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
    
    
    menuPrincipal mp = new menuPrincipal();
    static HumanSequencePlayer logged;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        Confirmar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setBackground(new java.awt.Color(153, 0, 0));
        user.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 181, -1));

        pass.setBackground(new java.awt.Color(153, 0, 0));
        pass.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 181, -1));

        Confirmar.setBackground(new java.awt.Color(153, 0, 0));
        Confirmar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        Confirmar.setForeground(new java.awt.Color(255, 255, 255));
        Confirmar.setText("Confirmar");
        Confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 130, 40));

        regresar.setBackground(new java.awt.Color(153, 0, 0));
        regresar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setText("Regresar");
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 347, 130, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Plantillas/LOGIN.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        menu menu = new menu();
        setVisible(false);
        
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_regresarActionPerformed

    /*
    Formato de dataBase.db
    
    String Nombre Completo
    int puntos
    long Fecha de creacion
    String username
    String password
    */
    
    private boolean autenticar(String username, String password) throws IOException{
        boolean autenticado = false;

        //Setea el archivo del que vamos a leer
        creacionDeUsuarios.dataBase = new RandomAccessFile("dataBase.db", "rw");
        
        //Asegura el puntero
        creacionDeUsuarios.dataBase.seek(0);
        
        //Recorrido de archivo
        while (creacionDeUsuarios.dataBase.getFilePointer() < creacionDeUsuarios.dataBase.length()){
            creacionDeUsuarios.dataBase.readUTF(); //Mueve el puntero la cantidad de Bytes que abarque el Nombre Completo del user
            creacionDeUsuarios.dataBase.skipBytes(12); //Skip 4 (int puntos) + 8 (long fecha) = 12 bytes
            
            //Extrae los datos correctos que usara de referencia
            String userRef = (String)creacionDeUsuarios.dataBase.readUTF();
            String passRef = (String)creacionDeUsuarios.dataBase.readUTF();
            
            //Verifica que el username y passsword ingresados concuerden
            
            if ((userRef).equals(username) && (passRef).equals(password)){
                autenticado = true;
            }
        }
        
        return autenticado;
    }
    
    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    public static HumanSequencePlayer userWithUsername(String username) throws IOException{
        creacionDeUsuarios.poblarUsers();
        
        for (HumanSequencePlayer current : creacionDeUsuarios.users){
            if (current.getUsername().equals(username)){
                return current;
            }
        }
        
        return null;
    }
    
    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        

        //Extrae los datos ingresados
        String username = user.getText();
        String password = String.valueOf(pass.getPassword());
        
        try {
            if (autenticar(username, password)){
                logged = userWithUsername(username);
                setVisible(false);
                
                mp.setVisible(true);
                mp.setLocationRelativeTo(null);
            } else {
                JOptionPane.showMessageDialog(null, "Autenticacion fallida");
            }
        } catch (IOException e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado en la autenticacion.\nFavor intente de nuevo");
        }
    }//GEN-LAST:event_ConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
